{% set name = "glycowork" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/glycowork-{{ version }}.tar.gz
  sha256: 05333fce2205059fa163b6e4b1ec0a28de45e29dc52cf8d4a4ab51ae99e4bb13

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python
    - scikit-learn
    - regex
    - networkx >=3.0
    - statsmodels
    - scipy
    - seaborn
    - xgboost
    - mpld3
    - pandas >=1.3
    - matplotlib-inline
    - python-louvain
    - pytorch  # [not win]
    - pytorch-cpu  # [win]

test:
  imports:
    - glycowork
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/BojarLab/glycowork
  summary: Package for processing and analyzing glycans
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Bribak
